name: simple_value_object_generator
description: A Dart code generator that simplifies the creation of Value Objects using Dart's extension type.
version: 1.0.3
homepage: https://github.com/r-koubou/dart_simple_barrel_generator
repository: https://github.com/r-koubou/dart_simple_barrel_generator

platforms:
  android:
  ios:
  linux:
  macos:
  windows:

environment:
  # extension types: available since Dart SDK 3.3
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  simple_value_object_annotation: ^1.0.0
  build: ^4.0.6
  source_gen: ^4.2.3
  analyzer: ^13.0.0


dev_dependencies:
  lints: ^6.1.0
  build_runner: ^2.15.0
